### ISSUE TITLE
client and server don't have same version

### ISSUE THREAD

**Issue by JoyceBabu** [blinkreaction/boot2docker-vagrant#10]
I am getting the following error message

```
FATA[0000] Error response from daemon: client and server don't have same version (client : 1.18, server: 1.17) 
```

How can I upgrade docker on the VM?

**Comment by JoyceBabu** [comment]
I was able to upgrade docker by downloading the binary directly

```
sudo /etc/init.d/docker stop
curl https://get.docker.io/builds/Linux/x86_64/docker-latest | sudo tee /usr/local/bin/docker > /dev/null
sudo /etc/init.d/docker start
```

**Comment by JoyceBabu** [comment]
That did not work as expected. The old version is restored when the VM is restarted.

**Comment by brikis98** [comment]
Same issue here.

**Comment by lmakarov** [comment]
@JoyceBabu, @brikis98 I've pushed a new release [v0.12.0](https://github.com/blinkreaction/boot2docker-vagrant/releases/tag/v0.12.0) with the most recent updated from the develop branch. This bumps the docker server version to v1.6.0 which will match the most recent docker client version as of today.

You will have to do a `vagrant destroy`, then `vagrant up` after you update.
Keep in mind that for now there is no non-destructive update path for this box - **you WILL lose all your containers inside the boot2docker-vagrant box**, since the box will be reinitialized.

**Comment by brikis98** [comment]
Thanks!
