### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by iturdikulov** [blinkreaction/boot2docker-vagrant#62]
Is possible to add ubuntu as vm.box + needed script to install docker (optionaly, maybe as plugin)?

Reason - digitalocean vagrant plugin not support vagrant box integrations (maybe AWS too)... And looks like DO not contain boot2docker image + official box more secure for me xD (hashicorp/precise64).

Yes I know - ubuntu as basebox - overkill.

Anyway - my message is just question, maybe I will just continue use my personal fork =)

**Comment by lmakarov** [comment]
@inomoz are you trying to use vagrant with DigitalOcean instead of VirtualBox?

We are using a customized boot2docker VM, which gets generated by docker-machine using the official boot2docker.iso. It is then packaged as a base box for vagrant.
A lot of provisioning tasks in Vagranfile currently heavily depend on the way this base box works.

Using a different base box would mean forking and refactoring what we currently have.
I'm open to PRs, but won't have the bandwidth (and a use case) for this at the moment.
