### ISSUE TITLE
Docker 1.10

### ISSUE THREAD

**Issue by smazurov** [blinkreaction/boot2docker-vagrant#73]
[Docker 1.10](https://blog.docker.com/2016/02/docker-1-10/) has been out for about a month and a half, any chance of upgrading to it? With it comes new format for `docker-compose` as well.

**Comment by lmakarov** [comment]
I had some weird issue with the 1.10 build of the base box and put it on hold a while back.

Also, since docker now comes with it's own embedded DNS server and new networking model, it will take some time to rethink the approach to DNS that this project is using (via https://github.com/blinkreaction/docker-dns-discovery).

No particular dates so far, but this is in the queue.

**Comment by lmakarov** [comment]
This is now available in `develop` via https://github.com/blinkreaction/boot2docker-vagrant/commit/9240ca1bb3c4522ce5a9497805c36853df025ddd

Please test the new base box and let me know if you run into any issues.

**Comment by lmakarov** [comment]
Available since [v1.5.0](https://github.com/blinkreaction/boot2docker-vagrant/tree/v1.5.0)
